version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        domain: ${DOMAIN}
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=admin@${DOMAIN}
    networks:
      - reverse-proxy
    restart: always

networks:
  reverse-proxy:
    external: true
