version: '3.9'

services:
  frontend:
    build:
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=repetitmeweb.ru
      - LETSENCRYPT_HOST=repetitmeweb.ru
      - LETSENCRYPT_EMAIL=mail@repetitmeweb.ru
    networks:
      - nginx-proxy
    restart: always

networks:
  nginx-proxy:
    external: true
